export const GET_PINTEREST_BOARD_START = "GET_PINTEREST_BOARD_START";
export const GET_PINTEREST_BOARD_SUCCESS = "GET_PINTEREST_BOARD_SUCCESS";
export const GET_PINTEREST_BOARD_FAIL = "GET_PINTEREST_BOARD_FAIL";
